miqa/core/rest/__init__.py, miqa/core/rest/user.py, miqa/urls.py
Add user view set + route `/users/me` to get currently logged in user
Changes paired with OpenImaging/miqa-web#8
=> User rest endpoint

development.md, miqa/core/management/commands/populate.py, miqa/core/rest/session.py, miqa/core/tasks.py, setup.py
- Added `development.md` for new developers (currently only documents docker approach)
- Added django admin command `populate`: Takes as arguments path to csv and username of existing user and populates database with core data; quick access version of import functionality
=> improve development 

README.md
=> Update note regarding login w/email

miqa/core/rest/user.py
Required for OpenImaging/miqa-web#29
=> send superuser status for permissions

learning/README.md, learning/nn_classifier.py, learning/requirements.txt
This is the current work-in-progress variant of the deep neural network pixel-based classifier. It classifies the images into either good or bad category.
=> Adding nn_classifier.py

miqa/core/rest/annotation.py, miqa/core/rest/experiment.py, miqa/core/rest/image.py, miqa/core/rest/scan.py, miqa/core/rest/session.py, miqa/core/rest/site.py, miqa/core/rest/user.py, miqa/urls.py
=> update permission_classes for all viewsets

client/src/django.js, client/src/main.js, client/src/store/index.js, miqa/core/rest/annotation.py, miqa/core/rest/experiment.py, miqa/core/rest/image.py, miqa/core/rest/scan.py, miqa/core/rest/scan_note.py, miqa/core/rest/session.py, miqa/core/rest/site.py, miqa/core/rest/user.py, miqa/settings.py
Change front-end to match updated back-end permissions: previously front-end was making requests before outh login occured, thus preventing entire site from loading
- Also remove unused `user` field in `djangoClient`
- Fix itk poolsize error
- Update default permissions class as per https://github.com/OpenImaging/miqa/issues/46#issuecomment-881462009
=> fix permissions/login error

development.md
- Correct invocation of `populate` command
- Add `makeclient` command step
- Update language for monorepo (as oppose to separate client repository)
=> README updates

README.md, miqa/settings.py, prod/README.md
Fix some of the issues I encountered when walking Curtis through the setup process.
=> Prod setup docs

client/src/components/DataImportExport.vue, client/src/django.js, miqa/core/rest/session.py
Resolves #63 
- Add spinner during export request
- Add error handling: display snackbar with error message (bad import path, etc.)
=> add export spinner + error handling

.gitattributes
Everyone needs to do step 1 from the instructions:
https://git-lfs.github.com/
Closes #124.
=> Enable git-lfs

miqa/core/rest/home.py, miqa/settings.py, miqa/urls.py
=> Redirect / to localhost:8081 in dev mode

prod/.env.template, prod/.gitignore, prod/DEVELOPMENT.md, prod/nginx.conf.template
`prod/README.md` is written for Jim/people who are deploying in a "real" environment with an existing nginx. `prod/DEVELOPMENT.md` is for devs to set up test deployments for the production docker-compose.
=> Prod dev docs

client/.eslintrc.js, client/package-lock.json, client/package.json, client/src/components/DataImportExport.vue, client/src/components/EmailDialog.vue, client/src/components/EmailRecipientCombobox.vue, client/src/components/ExperimentLockIcon.vue, client/src/components/GenericNavigationBar.vue, client/src/components/JSONConfig.vue, client/src/components/KeyboardShortcutDialog.vue, client/src/components/Layout.vue, client/src/components/NavigationTabs.vue, client/src/components/ScreenshotDialog.vue, client/src/components/SessionsView.vue, client/src/components/SiteConfig.vue, client/src/components/SiteTableContactCell.vue, client/src/components/SiteTableDisplayNameCell.vue, client/src/components/TimeoutDialog.vue, client/src/components/VtkViewer.vue, client/src/components/WindowControl.vue, client/src/components/girder/UserButton.vue, client/src/types.ts, client/src/views/Dataset.vue, client/src/vtk/constants.js, client/src/vue-utilities/prompt-service/Prompt.vue, client/src/vue-utilities/snackbar-service/Snackbar.vue
Converted six more files to use typescript, starting with the files that had the fewest errors. Added @types file to define User and Session. Finally, made some small changes to the eslintrc file so that typescript could be correctly interpreted.
=> Typescript Conversions #2

miqa/core/management/commands/populate.py, miqa/core/rest/session.py, miqa/core/tasks.py, miqa/core/tests/test_import.py, miqa/learning/nn_classifier.py
Changes the invocation of Celery tasks. Previously, these tasks were invoked synchronously, never getting sent to Celery. Now they are called asynchronously and the import task finishes before spawning a single background task to evaluate all the images in the import. Evaluation objects are created in this background task.
Resolves #126. Resolves #127. Resolves #128.
=> NN integration 3

miqa/core/tasks.py, miqa/learning/evaluation_models.py, miqa/learning/nn_inference.py, miqa/learning/nn_training.py, miqa/learning/requirements.txt, tox.ini
I only tested the training and single image evaluation. It would be good if @annehaley tested the evaluation on import.
=> Split the NN code into two files, training and inference

miqa/learning/nn_inference.py, miqa/learning/nn_training.py
This improves accuracy slightly.
=> Retain more information in first convolutional block

miqa/core/conversion/nifti_to_zarr_ngff.py, miqa/core/models/image.py
This will dynamically return the path to a Zarr store when requested.
=> Add zarr_path property to Image

client/src/components/VtkViewer.vue, client/src/store/index.ts
This PR adds colored crosshairs to the VtkViewer components.
I worked with Forrest Li to use VTK internals for proper visualization of the crosshairs. The last two commits on this PR are the results of live pair programming sessions with Forrest to ensure that rendering is done properly.
Resolves #170
=> Crosshairs

README.md, docker-compose.override.yml, miqa/core/rest/project.py
Two small fixes noted while helping @curtislisle set up his local environment
=> Deployment fixes

client/src/components/DataImportExport.vue, client/src/components/ExperimentsView.vue, client/src/components/ProjectSettings.vue, client/src/components/ProjectUsers.vue, client/src/django.ts, client/src/store/index.ts, client/src/types.ts, client/src/views/Projects.vue, miqa/core/rest/project.py, miqa/core/rest/user.py, miqa/core/tests/test_rest.py
This PR adds a users component to the Project Settings page so that a superuser may grant and revoke project permissions and all other users can see who else is on the project.
Resolves #184. Resolves #231.
=> Project settings page

client/src/components/EvaluationResults.vue, miqa/learning/nn_inference.py
Resolves #215.
These changes result in the following display of NN Evaluation results:
=> Invert negative results

miqa/learning/models/miqaT1-val0.pth, miqa/learning/models/miqaT1-val1.pth, miqa/learning/models/miqaT1-val2.pth, miqa/learning/models/miqaT1-val3.pth, miqa/learning/models/miqaT1-val4.pth, miqa/learning/nn_inference.py, miqa/learning/nn_training.py, miqa/learning/requirements.txt, setup.py
This adds augmentation of bad images during training phase. Inference remains unaffected.
Closes #27.
=> Use TorchIO for corrupting images with synthetic ghosting and motion

miqa/core/apps.py, miqa/core/rest/__init__.py, miqa/core/rest/accounts.py, miqa/core/signals.py, miqa/settings.py, miqa/templates/account_activate.html, miqa/templates/account_inactive.html, miqa/templates/account_reviewed.html, miqa/urls.py
Resolves #96 
This PR implements the following flow:
1. User signs up -> user receives verification email
2. User verifies email -> user is reset to inactive and a notification email goes to all admin users.
3. User tries to log in -> user sees page explaining that an admin needs to approve their account
4. Any admin clicks the link in the email -> Admin chooses to deny with rejection reason
5. User is kept inactive and is notified that their account was rejected
OR
4. Any admin clicks the link in the email -> Admin chooses to approve the account
5. User is switched to active and is notified that they may now log in.
Since the approval link is sent to all admin users, any admin may override the decision of another. The last admin's decision is used, but the new user will be notified of …
=> Admin account approval

miqa/OrientationTests2.cpp
This code was used to create 48 test images for #236. Original tests images were created manually using Slicer.
=> Sample code for creating all 48 3D orientations

client/package-lock.json, client/package.json, client/src/components/ControlPanel.vue, client/src/components/DataImportExport.vue, client/src/components/DecisionButtons.vue, client/src/components/ExperimentsView.vue, client/src/components/ProjectSettings.vue, client/src/django.ts, client/src/store/index.ts, client/src/types.ts, client/src/views/Projects.vue, miqa/core/models/project.py, miqa/core/rest/project.py
Resolves #192. 
This should be rebased and merged after #256 is merged.
=> Project page upgrade

client/src/components/EvaluationResults.vue, client/src/components/VtkViewer.vue, client/src/store/index.ts, client/src/utils/crosshairs.js, client/src/vtk/constants.js
Resolves #235.
Additional changes here fix the bug that the import and export paths did not appear in their tooltips as they should, as well as refactoring the cleanup on the `VtkViewer` component.
=> Fix example data

client/src/main.ts
I'm working on app load times generally, and this is some very low-hanging fruit.
=> Run startup XHRs concurrently

.github/workflows/ci.yml, README.md
For more reproducible package installation.
=> Use npm ci over npm install

docker-compose.override.yml
=> Fix npm builds for node>=17

miqa/core/management/commands/makeclient.py
=> Make makeclient idempotent

dev/README.md, tox.ini
=> Enable code coverage when running tests

client/src/components/EmailDialog.vue, client/src/django.ts, client/src/types.ts
=> Fix Email component not calling send

client/src/components/VtkViewer.vue
May resolve #326? I couldn't replicate the bug that the "next" button no longer works after resize.
=> Fix window resize bug
