OpenImaging/miqa

.github/workflows/build-docker.yml

The build-docker action was running on merges to `main`, but our main
branch is `master`.

Fix build action branch typo

---

client/.env.production
miqa/core/management/commands/makeclient.py
miqa/core/rest/__init__.py
miqa/core/rest/home.py
miqa/settings.py
miqa/urls.py
prod/.env
prod/README.md
prod/django.Dockerfile
prod/docker-compose.yml
tox.ini

`miqa-web` was already copied into the `client` directory in #59.
* Add a new directory `prod` which contains all the docker/docker-compose/documentation stuff
* The docker image builds the django app, builds the web client, then plops the built artifacts into Django's `staticfiles`. Django's whitenoise app will then serve it under `/static/`. The frontend configuration has been updated to use relative URLs since Django and the web client are now hosted on the same domain/port.
* To get the `index.html` to be served from `/` rather than `/static/index.html`, I registered `staticfiles` as a template directory, then created a `TemplateView` which served `index.html` and registered it with the url `/`. This will technically break in development, but in development we use `npm run serve` …

Production docker compose

---

miqa/settings.py
prod/nginx.conf.example

The reverse proxy was doing SSL termination and sending HTTP traffic to
django, which was then doing SSL redirection instead of handling the
traffic.
* SECURE_SSL_REDIRECT is set to False to stop this behavior.
* SECURE_PROXY_SSL_HEADER is set to ('HTTP_X_FORWARDED_PROTO', 'https')
so that when the reverse proxy sets the `X-Forwarded-Proto` header,
Django will treat the HTTP traffic as HTTPS.
The nginx example is also update to set `X-Forwarded-Proto`.

Disable SSL redirect and set SECURE_PROXY_SSL_HEADER

---

client/.env.production
miqa/settings.py
prod/.env.template
prod/django.Dockerfile
prod/docker-compose.yml
prod/nginx.conf.example

* `CSRF_TRUSTED_ORIGINS` is necessary for nginx configurations that use `upstream` blocks.
* `VUE_APP_OAUTH_API_ROOT` is necessary for the OAuth client to work, the previous value specified in client/.env.production was actually completely broken and failing silently.

Fix production

---

.github/workflows/ci.yml

We are now running `tox` in CI, but since the client code also lives in CI, we should also be running `yarn lint`.

Add yarn lint to GitHub Actions

---

client/src/components/VtkViewer.vue
client/src/django.js
client/src/store/index.js
client/src/utils/fill2DView.js
client/src/vtk/proxy.js

I found a way to piggy back on our existing view generators so I didn't have to figure out how to respecify the whole render pipeline. The `ScreenshotView2D_x/y/z` are copies of `View2D_x/y/z`, but are not mounted in the DOM. Instead, when the screenshot button is clicked, they are mounted in a disconnected div, sized appropriately, and used to capture the screenshot.

Fix screenshots

---

README.md
docker-compose.override.yml

Since the web client is now hosted in the same repo, it makes sense to
include it in the same development configuration.

Add web client to dev docker-compose file

---

README.md

These currently fail, so remove from developer documentation.
Developments to get them passing are tracked in #84.

Remove type tests from README

---

miqa/core/rest/annotation.py
miqa/core/rest/experiment.py
miqa/core/rest/image.py
miqa/core/rest/scan.py
miqa/core/rest/scan_note.py
miqa/core/rest/session.py
miqa/core/tests/test_rest.py

Right now in master, users are unable to perform imports or do any other write operation without the session lock, which currently does not have a UI or any descriptive error messages on how to obtain the session lock.
Remove `UserHoldsSessionLock` from the permissions of all the views for now so that `master` is usable.

Disable session locks

---

client/src/components/ExperimentLockIcon.vue
client/src/components/SessionsView.vue
client/src/django.js
client/src/store/index.js
client/src/views/Dataset.vue

Add a lock button to the UI that indicates who currently owns the experiment lock, and locks/unlocks when pressed.
The lock is present both in the session browser and in the dataset view. The notes and decision inputs are disabled when the lock is not owned by the current user.

Experiment lock UI

---

miqa/core/tasks.py
miqa/core/tests/conftest.py
miqa/core/tests/test_import.py

Jim's problems in #117 are utterly inscrutable because we attempt to wrap any errors in another exception, which obscures the stack trace. By removing the error handling entirely, we let django throw a 500 error on failed imports and print the stack trace.
Also add some meaningful tests for import.

Better import errors

---

miqa/learning/nn_classifier.py

To avoid `Task miqa.core.tasks.evaluate_data[4c98627b-d341-47ea-9a6b-a7836d515f00] raised unexpected: AssertionError('daemonic processes are not allowed to have children')`

Do not create an extra worker process in evaluate1

---

client/src/components/EmailDialog.vue
client/src/components/ExperimentsView.vue
client/src/components/NavigationTabs.vue
client/src/components/VtkViewer.vue
client/src/store/index.ts
client/src/views/Dataset.vue

Basically a big find/replace for "project" to "scan". Originally in the frontend scans were referred to as "sessions", as in a person having a session in an MRI. "session" was find/replaced to "project" in an earlier PR. I need to do this renaming now so I can add stuff for multi project support.

Rename project scan

---

client/src/components/ControlPanel.vue
client/src/components/ExperimentsView.vue
client/src/components/Navbar.vue
client/src/components/UserButton.vue
client/src/django.ts
client/src/store/index.ts
client/src/views/Projects.vue
miqa/core/rest/experiment.py
miqa/core/rest/user.py
miqa/core/tests/test_rest.py

The target bugs for this final PR of the control panel redesign are as follows:
- The initial for the decision made on a scan (displayed in the Experiment List as G, B, or O) should use the last decision made on that scan.
- Automatic locking and unlocking of an experiment when a reviewer opens it should work with no unexpected behavior, especially when two reviewers are interested in the same experiment.
- When an Experiment note is updated and successfully saved, the user may flip to the next scan or frame and will see the previous value again
- When a user is flipping through frames, the values for window width and window level are adjusted automatically as a guess based on the attributes of the frame. However, if the user manually sets either of these values, they should not be …

Control panel redesign (3/3)

---

client/src/components/ControlPanel.vue
client/src/components/VtkViewer.vue
client/src/views/Frame.vue

There were several race conditions where objects loaded asynchronously
would sometimes be null, causing console errors.

Fix console errors

---

.github/workflows/ci.yml

This is mostly to do type checking which apparently isn't done with `lint`, but also ensures there are no other build problems.

Run yarn build in CI

---

setup.py

Resolves #249. We specified that our version of Django is greater than 3.2, and since Django 4.0 came out today, the last CI run attempted to use Django 4.0. This broke the migrations for `oauth2_provider`. This PR simply specifies that we should use a version of Django between 3.2 and 4.0.

Fix failing CI test

---

client/src/components/DataImportExport.vue
client/src/django.ts
miqa/core/conversion/import_export_csvs.py
miqa/core/rest/project.py
miqa/core/tasks.py
miqa/core/tests/test_import.py

Resolves #182.
This might resolve #251; I couldn't replicate the issue with an unpopulated import file, but I did notice that the import error messages were always vague. This PR addresses that by propagating server-side errors to the snackbar error message display in the frontend.

Clearer import errors

---

.gitignore

Not sure how the previous buggy version got in there. This seems like a sane gitignore policy for now, unless we want to start having zarr files in source control.

Ignore all sample zarr files

---

client/src/components/VtkViewer.vue

It now no longer overflows the container. Before:
After:

Improve vtk viewer toolbar positioning

---

client/src/components/VtkViewer.vue
client/src/store/index.ts
client/src/utils/crosshairs.js

After the changes made to `VtkViewer` to fix the camera placement for flipped/rotated/axis-switched images, the assumptions made for drawing crosshairs were no longer correct. This PR changes the crosshairs logic to account for this.

Fix crosshairs

---

client/src/components/ControlPanel.vue
client/src/components/ExperimentsView.vue
client/src/router.ts
client/src/store/index.ts
client/src/views/Frame.vue

Resolves #233. I went with @dchiquito's suggestion to include the project id in the url.
I left the following line in just in case there is some failure to load the project:
```
this.$router.replace('/').catch(this.handleNavigationError);
```
But, in most cases, this line is not reached.

Enable navigating directly to Frame

---

miqa/learning/models/miqaT1-val0.pth
miqa/learning/models/miqaT1-val1.pth
miqa/learning/models/miqaT1-val2.pth
miqa/learning/models/miqaT1-val3.pth
miqa/learning/models/miqaT1-val4.pth
miqa/learning/nn_training.py

5-fold cross-validation test on the big dataset says that ghosting quality factor 8 works better than 7. On just the first fold, 7 worked slightly better.

Ghosting quality 8 works best on the 5 folds of the big set

---

miqa/core/rest/project.py
miqa/core/tests/test_rest.py

Having two parallel serializers on the backend and one type definition on the frontend was causing a frontend problem to occur when creating a new project (User would have to refresh to see the new project). This PR merges the `ProjectSerializer` class with the `ProjectRetrieveSerializer`.

Merge Project serializers

---

client/src/components/VtkViewer.vue

Resolves #277.
There are two approaches in the two below commits. The first introduces a logic in the `onWindowResize` method such that `fill2DView` is not called if the zoom level is manually set by the user. However, it may be simpler to remove this definition of the `onWindowResize` from `VtkViewer` entirely. It is unclear the original purpose for this function, because without it expected behavior is still seen. 
Could I get help determining whether it really is the case that we don't need that function anymore?

Fix Zoom bug

---

client/src/store/index.ts
client/src/types.ts
client/src/utils/registerReaders.js
miqa/core/rest/frame.py
miqa/core/tests/test_rest.py

Resolves #262 
There were some places in the frontend that we used a magic filename `nifti.nii.gz` passed into the file reader, so I had to add a bit to the Frame serializer on the backend to tell us what the true file extension was.

Add support for nrrd and mgz file types

---

client/src/components/VtkViewer.vue
client/src/utils/crosshairs.js

During yesterday's demo, I realized that the version that fixed rotated images broke axis-swapped images. This fix works for both.

Fix place crosshairs

---

client/src/components/DataImportExport.vue
client/src/components/ProjectSettings.vue
client/src/django.ts
client/src/store/index.ts
client/src/types.ts
client/src/views/Projects.vue
miqa/core/conversion/import_export_csvs.py
miqa/core/rest/__init__.py
miqa/core/rest/global_settings.py
miqa/core/rest/project.py
miqa/core/tasks.py
miqa/core/tests/test_import.py
miqa/core/tests/test_rest.py
miqa/urls.py

This PR introduces four new endpoints to accompany the `GlobalSettings` singleton model:
1. GET /global/settings
2. PUT /global/settings
3. POST /global/import
4. POST /global/export
Additionally, this PR leverages those endpoints on the frontend to include an admin-only UI for editing the values of th global import path and export path, as well as performing global imports/exports

Global settings frontend

---

client/src/components/ProjectSettings.vue
client/src/views/Projects.vue
miqa/core/rest/project.py
miqa/core/tests/test_import.py

Anyone with project access now is able to click the import/export buttons. They are not allowed to change import/export paths or the global import setting.

Allow anyone with project access to import/export

---

client/src/components/EmailDialog.vue
client/src/components/ScreenshotDialog.vue
client/src/components/VtkViewer.vue
client/src/store/index.ts
client/src/utils/helper.js
client/src/views/Frame.vue
client/src/vtk/viewManager.js

Fix Screenshot captures
